//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortScanner.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid IP address..
        /// </summary>
        internal static string InvalidIpAddress {
            get {
                return ResourceManager.GetString("InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message type..
        /// </summary>
        internal static string InvalidMessageType {
            get {
                return ResourceManager.GetString("InvalidMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port [0] is not a valid port..
        /// </summary>
        internal static string InvalidPort {
            get {
                return ResourceManager.GetString("InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in port input..
        /// </summary>
        internal static string InvalidPortInput {
            get {
                return ResourceManager.GetString("InvalidPortInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port [0] in [1] is invalid..
        /// </summary>
        internal static string InvalidPortInRange {
            get {
                return ResourceManager.GetString("InvalidPortInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port range format in [0]..
        /// </summary>
        internal static string InvalidPortRange {
            get {
                return ResourceManager.GetString("InvalidPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one valid port must be specified..
        /// </summary>
        internal static string NoPortsSpecified {
            get {
                return ResourceManager.GetString("NoPortsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address is required..
        /// </summary>
        internal static string RequiredIpAddress {
            get {
                return ResourceManager.GetString("RequiredIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port scan aborted..
        /// </summary>
        internal static string ScanAborted {
            get {
                return ResourceManager.GetString("ScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port scan sucessfully completed..
        /// </summary>
        internal static string ScanCompleteSuccessful {
            get {
                return ResourceManager.GetString("ScanCompleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan error.
        /// </summary>
        internal static string ScanErrorTitle {
            get {
                return ResourceManager.GetString("ScanErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan results.
        /// </summary>
        internal static string ScanResultsTitle {
            get {
                return ResourceManager.GetString("ScanResultsTitle", resourceCulture);
            }
        }
    }
}
